# Generated by Django 3.2.19 on 2023-06-30 22:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/dif9bjzee/image/upload/v1688163762/backgroud_hwsqzo.png', max_length=255, null=True, verbose_name='image'),
        ),
    ]
