# Generated by Django 3.2.19 on 2023-07-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_auto_20230709_2221'),
        ('users', '0005_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True, default='Foodie in and out..!', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='fav_food',
            field=models.CharField(blank=True, default="What's your favourite cuizine?", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='firstname',
            field=models.CharField(blank=True, default='Firstname', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='pinned_restaurants',
            field=models.ManyToManyField(blank=True, related_name='to_visit', to='review.Restaurant'),
        ),
        migrations.AddField(
            model_name='profile',
            name='reviewed',
            field=models.ManyToManyField(blank=True, related_name='reviewed', to='review.Restaurant'),
        ),
        migrations.AddField(
            model_name='profile',
            name='surname',
            field=models.CharField(blank=True, default='Surname', max_length=50, null=True),
        ),
    ]
