# Generated by Django 3.2.19 on 2023-07-17 10:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20230710_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/dif9bjzee/image/upload/v1689590568/profile-gda8c660e4_640_z54qoi.jpg', max_length=255, null=True, verbose_name='image'),
        ),
    ]
