# Generated by Django 3.2.19 on 2023-07-09 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_rename_reviews_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='comment_text',
            field=models.TextField(default='Type in a review here...'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
