# Generated by Django 3.2.19 on 2023-07-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_alter_restaurant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='RestaurantId',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
    ]
